name: Just Go Away Travel
favicon: null
layout_spectrum: 0.6161034984979779
typography_spectrum: 0.05981805128976703
title: Just Go Away Travel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1612880842294544
  lightness: 0.18480741535313427
  saturation: 0.8806607488077134
  rhythmicContrast: 0.09134962409734726
purpose: []
